### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by sqnczzl** [MaxKeyTop/MaxKey#13]
**Describe the bug**
登录时由于session不一致导致无法登录

**Comment by shimingxy** [comment]
MaxKey同时启用两个端口80和443端口，由于在访问时使用了http访问，然后再通过https访问，导致产生两个不同的session，请停止MAXKEY服务，清除浏览器cookie，然后使用https来访问；该问题已经在最新的代码解决，下一版本发布
