### ISSUE TITLE
CAS 应用跳转地址BUG

### ISSUE THREAD

**Issue by inlhx** [MaxKeyTop/MaxKey#25]
org.maxkey.authz.cas.endpoint.CasAuthorizeEndpoint 类中
59行
casDetails.setService(casService);
List<AppsCasDetails> casDetailsList=casDetailsService.query(casDetails);

如果如果cas是全路径拦截，请求部分url时会出现与服务器存储上下文地址不能完全匹配情况，例如：
maxkey注册的casclient是 http://localhost:8080/examples/
但是如果超时 访问到 http://localhost:8080/examples/abc/test.html  会出现casDetailsList为空，因为无法匹配当前请求的url是数据库记录的：http://localhost:8080/examples/  执行sql日志如下：
org.maxkey.persistence.mapper.AppsCasDetailsMapper.query:137 - ==>  Preparing: SELECT * FROM `MXK_APPS_CAS_DETAILS` WHERE (`SERVICE`=?)
org.maxkey.persistence.mapper.AppsCasDetailsMapper.query:137 - ==> Parameters: http://localhost:8080/examples/abc/test.html (String)

**Comment by shimingxy** [comment]
修复
