### ISSUE TITLE
CAS单点登出问题

### ISSUE THREAD

**Issue by inlhx** [MaxKeyTop/MaxKey#26]
例如平台集成了2个应用，平台登出后，被集成的1应用 casclient还处于登录状态，必须要清除cookie后该应用才登出，
但是2casclient 还处于登录状态，没达到单点登出效果，应该像cas一样，主服务器登出将自动通知其他登录的应用登出。

**Comment by shimingxy** [comment]
后续优化，关闭浏览器

**Comment by guozhanxian** [comment]
我觉得这个是一个高优先级的问题，应该先解决。

**Comment by shimingxy** [comment]
支持CAS单点注销，非CAS提供其他方式实现注销
