### ISSUE TITLE
maxkey-web-manage 项目配置文件的验证码启用不启用配置未生效

### ISSUE THREAD

**Issue by alanland** [MaxKeyTop/MaxKey#34]
**Describe the bug**

maxkey-web-manage 项目配置文件的验证码启用不启用配置未生效

**To Reproduce**
1. Edit  `maxkey-web-manage/src/main/resources/maxkey.properties`, set `config.login.captcha=false`,
2. 运行项目 maxkey-web-manage,
3. 访问 `http://localhost:9521/maxkey-mgt/login`
4. 验证码依然存在。

**Expected behavior**
配置了不启用验证码，验证码不应该出现。

**Screenshots**

![image](https://user-images.githubusercontent.com/2202150/97982297-88e4bf00-1e0e-11eb-9405-c050a6386158.png)

**Comment by shimingxy** [comment]
已修复
