### ISSUE TITLE
如何在linux安装部署

### ISSUE THREAD

**Issue by linqingping** [MaxKeyTop/MaxKey#39]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shimingxy** [comment]
参见 https://maxkey.top/zh/conf/tutorial.html

**Comment by linqingping** [comment]
谢谢啦,这个文档看过了,但这个文档还需要在我win上执行生成数据库代码不是很方便！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaxKeyTop/MaxKey"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月10日(星期四) 下午4:19
收件人:&nbsp;"MaxKeyTop/MaxKey"<MaxKey@noreply.github.com&gt;;
抄送:&nbsp;"北冥有鱼"<1959132391@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MaxKeyTop/MaxKey] 如何在linux安装部署 (#39)





 
参见 https://maxkey.top/zh/conf/tutorial.html

**Comment by shimingxy** [comment]
对应的MYSQL脚本在，文档没有详细说明，后续补充上
https://github.com/MaxKeyTop/MaxKey/tree/master/sql
